# Site settings
title: ePages Documentation
email: documentation@epages.com
description: >
  This is the primary source of trust for ePages beloved third
  party developers.
baseurl: "/epages-docs"
url: "http://epages-de.github.io"
github_url: "https://github.com/ePages-de/epages-docs"
raml_root: _raml/api.raml

# Build settings
markdown: ExtendedMarkdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Deployment settings
deployment:
  type: git
  repo: git@github.com:ePages-de/epages-docs.git
  branch: gh-pages

# Search index settings
search:
  host: localhost:9200
  index:
    mappings:
      page:
        properties:
          url:
            type: string
            analyzer: keyword
          title:
            type: string
            analyzer: english
          content:
            type: string
            analyzer: english
